// GERADO AUTOMATICAMENTE POR build-chamas.js
// NAO EDITAR A MAO.
// Gerado em: 2026-09-30T20:59:46.934Z

const MICROCONTOS = [
  {
    titulo: "O peso da conta",
    texto: "A porta bateu com aquele rangido de quem tem muita pressa pra fugir do frio. Era um pescador, rosto talhado pelo sal e pelo vento, daqueles que a gente vê passar na costa quando o mar tá bravo demais pra peixe comum. Ele não esperou convite. Caminhou até o balcão com o passo pesado de quem carrega um erro há muitos invernos.\n\nPousou um saco pequeno, amarrado com couro cru, em cima da madeira. O barulho do que tinha dentro não era de moeda. Era surdo. Denso.\n\n— O inverno tá no fim — ele disse, sem me encarar. — A dívida também.\n\nEu conheço esse tipo. O homem que guarda o que deve embaixo do assoalho pra não esquecer que um dia foi covarde. Ele não queria perdão. Queria silêncio.\n\nEmpurrei o saco de volta.\n\n— Se for o que eu tô pensando, o mar já cobrou esse preço.\n\nEle travou. Olhou pra mim e vi o alívio brigando com a vergonha naqueles olhos de água salgada. O homem que vive de rede sabe que não adianta tentar pescar o passado. O que ficou lá, ficou lá. \n\n— Não preciso disso — eu disse, mais seco que o inverno lá fora. — Mas aceito o brinde. Pela volta.\n\nEle suspirou. Um som que parecia gelo quebrando depois de meses de espera. Sentou, pediu o hidromel e, pela primeira vez na vida, soltou os ombros. \n\nNinguém carrega esse peso pra sempre. Ou a dívida consome a alma, ou a gente entrega pro mar levar. \n\n#chamas"
  },
  {
    titulo: "O peso da promessa",
    texto: "A porta rangeu com o último suspiro do inverno. Era um velho. Rosto marcado pelas tempestades, mãos trêmulas de tanto puxar rede. Ele não pediu hidromel. Colocou um saco de couro pequeno no balcão, entre nós. O couro estava gasto, encardido de mar e sal.\n\n— Demorei — ele disse. A voz soava como madeira rangendo em casco.\n\nEu não perguntei o que tinha dentro. Conheço esse olhar. É o olhar de quem passou décadas esperando o gelo derreter para, finalmente, conseguir andar sem o peso de um segredo pendurado no pescoço. \n\nEle empurrou o saco. O som foi abafado, pesado.\n\n— Não devo mais nada.\n\n— A gente nunca deixa de dever nada — respondi. — Mas a gente pode escolher o que deixar para trás.\n\nO velho soltou um suspiro longo, soltando os ombros pela primeira vez em muitos invernos. Ele olhou em volta, viu que a Taverna Fenrir estava em silêncio, apenas o estalar do fogo na lareira.\n\nEu guardei o saco sob o balcão. Não abri. Não importa o que ele trouxe. O que importava era que ele, pela primeira vez, não estava procurando uma saída. Ele estava procurando onde sentar.\n\n— Fica — eu disse, apontando o banco mais próximo da lareira. — A noite ainda está fria.\n\nEle sentou. O peito subiu e desceu mais leve. A dívida não estava no saco. Estava na coragem de vir até aqui e colocar o passado sobre o balcão.\n\n#chamas"
  },
  {
    titulo: "A Mulher do Mar",
    texto: "Faz poucos dias que Sigrid começou a frequentar o balcão.\n\nNão sei muito sobre ela. Sei que vem no fim da tarde, pede hidromel, senta perto da janela. Não fala com ninguém. Bebe devagar. Vai embora antes da lua subir.\n\nNa terceira noite, perguntei ao Bardo se ele sabia quem ela era. Ele disse:\n\n— É do vilarejo do sul. O marido partiu em jornada faz mais de seis meses. Sem notícia desde então.\n\nEu não entendi na hora. Depois entendi.\n\nAquele olhar. Eu conhecia aquele olhar.\n\nNão é olhar de quem perdeu. É olhar de quem ainda não sabe o que perdeu. Eu vi nas mulheres do bando quando os homens partiam. E vi na minha própria cara no reflexo da água depois que perdi alguém que eu não vou contar hoje.\n\nReconhecer é perigoso. Porque quando a gente reconhece, a gente sente junto. E sentir junto dá trabalho. É mais fácil servir a bebida, dizer boa noite, deixar a pessoa ir.\n\nMas eu não abri essa taverna pra isso.\n\nNa quarta noite, sentei na frente dela. Puxei o banco, dobrei os braços na mesa, e disse:\n\n— Sigrid.\n\nEla ergueu os olhos.\n\n— Eu não sei do teu marido. Ninguém aqui sabe. Não tem carta que atravesse o mar. O que existe é knarr — e quando um knarr volta, ele traz notícia ou traz silêncio. O teu ainda não voltou. Isso não é resposta. É só espera.\n\nEla não chorou. Ficou olhando pra mesa.\n\n— Eu vi batalha, Sigrid. Muita. Mais do que mulher deveria ver. E vou te dizer uma coisa que talvez não sirva pra ti agora, mas que é a única verdade que eu carrego: guerra não volta atrás. Homem que entra numa jornada ou volta, ou fica. Não existe terceira opção. E enquanto ele não volta, tu tá aqui. Viva. Sentada no meu balcão. Bebendo do meu hidromel. Isso não é pouco.\n\nEla ficou um tempo quieta. Depois bebeu de um gole. Depois comeu o que eu trouxe. Depois dormiu num dos quartos de cima.\n\nFaz quatro dias que ela dorme aqui.\n\nNão sei se o marido volta. Não sei se tá vivo. Não sei se merece a espera dela. Só sei que enquanto ela tiver cama quente, caneca cheia e banco reservado perto do fogo, ela tá viva. E enquanto ela tá viva, tem esperança. E enquanto tem esperança, tem motivo pra acender o fogo amanhã.\n\nA taverna não devolve maridos. Não cura luto. Mas segura a vela enquanto a tempestade passa."
  },
  {
    titulo: "A Resposta",
    texto: "Ele entrou com a chuva. Jovem. Não tinha nem vinte invernos. Sentou no banco da frente e ficou me olhando como quem espera resposta antes da pergunta.\n\n— Você foi do Lobo Cinzento.\n\nNão era pergunta. Era coisa que ele ouviu em algum canto de estrada.\n\n— Fui.\n\n— Eu quero entrar.\n\nPousei a caneca que tava limpando. Olhei pra ele. Cabelo molhado, mãos calejadas de coisa pequena, olhar de quem já decidiu antes de entender.\n\nEu conhecia aquele olhar. Já tinha tido ele.\n\n— Sabe remar? — perguntei.\n\n— Não.\n\n— Sabe segurar machado?\n\n— Não.\n\n— Sabe o que faz quando um homem morre do teu lado?\n\nEle ficou quieto.\n\nServi hidromel. Sem cobrar. Pousei na frente dele.\n\n— Bebe. Depois a gente conversa.\n\nEle bebeu. Eu fiquei olhando o fogo.\n\n— Quantos invernos tu tem?\n\n— Dezenove.\n\nEu tinha catorze quando entrei.\n\n— Tu tem raiva — eu disse. — Raiva não enche remo.\n\n— Eu sei lutar.\n\n— Não sabe. Sabe bater. É diferente.\n\nEle abaixou a cabeça. Eu continuei limpando o balcão.\n\n— Volta quando tiver uma coisa que tu quer mais do que vingança. Aí a gente vê.\n\nEle levantou. Pousou a moeda que eu não cobrei. Foi até a porta.\n\nAntes de sair, virou.\n\n— Como é que eu vou saber?\n\nOlhei pra ele. De verdade, dessa vez.\n\n— Tu vai acordar de manhã e a primeira coisa que tu vai pensar não vai ser em quem te fez mal.\n\nEle foi embora.\n\nFechei a porta. Apaguei a lamparina."
  },
];
